In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1, 2, 3, 4, 5 ])
a

array([1, 2, 3, 4, 5])

In [7]:
a[2]

np.int64(3)

In [8]:
a[2]= 10

In [9]:
a

array([ 1,  2, 10,  4,  5])

In [10]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

Multi Dimensional Array
